# Generated by Django 4.2.6 on 2024-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField(max_length=300)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('num', 'num')], default='num', max_length=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
