# Generated by Django 4.2.6 on 2024-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_gallery_view1_gallery_view10_gallery_view2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='rating',
            field=models.CharField(blank=True, choices=[('premium', 'premium'), ('standard', 'standard'), ('deluxe', 'deluxe')], default='rating', max_length=10, null=True),
        ),
    ]
