# Generated by Django 4.2.6 on 2024-05-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_gallery_header_alter_gallery_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
